# Generated by Django 4.2 on 2026-01-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_faceimageresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('headers', models.JSONField()),
                ('body', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('files_count', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
